spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social
    username: postgres
    password: 9567
  mvc:
    hiddenmethod:
      filter:
        enabled: on

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 305406201618-rekpsbh178kk9kog749g0dladc54j9qn.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:  openid, email, profile


jwt_secret: secret